eureka:
 client:
  register-with-eureka: true
  fetch-registry: true
  service-url:
   defaultZone: http://eureka-server:8761/eureka/
 instance:
  hostname: localhost
  
  spring:
   zipkin:
    base-url: http://zipkin-server:9411/ 
