eureka:
 client:
  register-with-eureka: true
  fetch-registry: true
  service-url:
   defaultZone: http://eureka-server:8761/eureka/
 instance:
  hostname: eureka-server
  
spring:
  zipkin:
   base-url: http://zipkin-server:9411/ 
  datasource:
    url: jdbc:mysql://standalone:3306/userreg
    username: sa
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
